/*
 * This source file was generated by the Gradle 'init' task
 */
package poop;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {

    @Test 
    @DisplayName("My Test!")
    public void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        //fail("you suck");
        
    }
}
