/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

import org.junit.jupiter.api.Test;

import project.util.Utility;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

import javax.xml.crypto.Data;

import org.junit.jupiter.api.DisplayName;

class TestManager {

    // @Test
    // @DisplayName("Debug")
    // public void debug(){
    //     assertEquals(1, 1);
    // }
}
