/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class TestManager {

    @Test 
    @DisplayName("My Test!")
    public void appHasAGreeting() {

        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        //fail("you suck");
        
    }
}
